# Generated by Django 5.2.17 on 2026-09-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_experience_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='period_label',
            field=models.CharField(blank=True, help_text='2022 - 2025', max_length=50),
        ),
    ]
