# Generated by Django 5.2.17 on 2026-09-13 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_seed_experience_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lakon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('desain', 'Desain'), ('musik', 'Musik'), ('seni', 'Seni'), ('tulisan', 'Tulisan'), ('dapur', 'Dapur'), ('coding', 'Coding')], default='seni', max_length=20)),
                ('proof', models.TextField(help_text='Bukti/cerita singkat yang muncul saat kartu diklik')),
            ],
        ),
    ]
