# Generated by Django 5.2.17 on 2026-09-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lakon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lakon',
            name='proof',
        ),
        migrations.AddField(
            model_name='lakon',
            name='caption',
            field=models.CharField(blank=True, help_text='Keterangan singkat opsional', max_length=150),
        ),
        migrations.AddField(
            model_name='lakon',
            name='photo',
            field=models.CharField(blank=True, help_text='Path relatif, misal: img/lakoni/kalimba.jpg', max_length=255),
        ),
    ]
