# Generated by Django 5.2.17 on 2026-09-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_lakon_proof_lakon_caption_lakon_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lakon',
            name='caption',
        ),
    ]
